### ISSUE TITLE
Подумайте, как не дублировать это 3 раза

### ISSUE THREAD

**Issue by coursar** [igoridze/calculate_cashback#1]
https://github.com/igoridze/calculate_cashback/blob/34f6a16b7b9c323c9189680ffad5da3da337e51c/app/calculate_cashback.py#L32-L34

**Comment by igordriagunov** [comment]
https://github.com/igoridze/calculate_cashback/blob/master/app/calculate_cashback.py#L46-L49

https://github.com/igoridze/calculate_cashback/blob/41e81008bfaaa0e507375876fad6f3b90f136bd6/app/calculate_cashback.py#L46-L49

**Comment by coursar** [comment]
Можно было вынести эту проверку в конец функции
